### PR TITLE
Add docs for Timeline

### PR DESCRIPTION
**Pull request by AnnMarieW**
Added the docs for the Timeline Component

### CODE REVIEW

**Comment by AnnMarieW** [comment]
@snehilvj   I was puzzled about why the interactive demo wasn't working.   It appears that the `Timeline` component is missing the `id` prop :upside_down_face:

**Comment by snehilvj** [comment]
🤦‍♂️🤦‍♂️
I need to be better at reviewing PRs. I'll do a release soon.

**Comment by snehilvj** [comment]
Done

**Comment by AnnMarieW** [comment]
It would also be nice to update the [Timeline PropTypes](https://github.com/snehilvj/dash-mantine-components/blob/master/src/lib/components/Timeline.react.js#L55) so it refers to `TimelineItems` rather than `<Timeline.Item /> `

**Comment by snehilvj** [comment]
> The gallery example does not create this warning, even if `reverseAction` is set for the component.

It's because the correct name for the this prop is `reverseActive`.

> I was trying to recreate the example from the [mantine docs](https://mantine.dev/core/timeline/) but wasn't able to get the link to display in-line without using css or `html.Span`.

You can just pass everything in the dmc.Text component like this:
```python
dmc.Text(
  [
      "You've created new branch ",
      dmc.Anchor("fix-notification", href="#", size="sm"),
      " from master",
  ],
  color="dimmed",
  size="sm",
)
```
I have taken care of this now, so you don't have to make any changes for now.

**Pull request merged**
